import { defineConfig } from "@playwright/test";

const baseURL = "http://127.0.0.1:3102";

export default defineConfig({
  testDir: "./tests/performance",
  testMatch: "browser-shell-performance.spec.ts",
  fullyParallel: false,
  workers: 1,
  retries: 0,
  reporter: "line",
  projects: [
    { name: "desktop-1366" },
    { name: "mobile-360" },
  ],
  webServer: {
    command: "npm run build && npm run start -- --hostname 127.0.0.1 --port 3102",
    url: baseURL,
    reuseExistingServer: false,
    timeout: 90_000,
    env: {
      APP_ENVIRONMENT: "test",
      APP_PUBLIC_ORIGIN: baseURL,
      PROVIDER_BILLING_MODE: "free_only",
      LOCAL_PROVIDER_CREDENTIAL_MODE: "contract_only",
      CREDENTIAL_VAULT_PROVIDER: "disabled",
      ENABLE_SYNTHETIC_PROVIDER: "false",
      ENABLE_LIVE_TRADING: "false",
      ENABLED_PAID_ADAPTERS: "",
      ENABLED_PAID_ROUTES: "",
      ENABLED_PAID_SCHEDULES: "",
      F1_SCRIPTED_PROVIDER_DELAY_MS: "20",
      RUN_ALPACA_BASIC_DATA_CONTRACT: "false",
      RUN_KIS_PERSONAL_DATA_CONTRACT: "false",
      RUN_ALPACA_PAPER_READ_CONTRACT: "false",
      RUN_KIS_PAPER_READ_CONTRACT: "false",
      RUN_ALPACA_PAPER_ORDER_CONTRACT: "false",
      RUN_KIS_PAPER_ORDER_CONTRACT: "false",
      ALPACA_API_KEY_ID: "",
      ALPACA_API_SECRET_KEY: "",
      KIS_APP_KEY: "",
      KIS_APP_SECRET: "",
      GOOGLE_IDENTITY_ENABLED: "false",
      GOOGLE_IDENTITY_CLIENT_ID: "",
      GOOGLE_IDENTITY_CLIENT_SECRET: "",
      GITHUB_IDENTITY_ENABLED: "false",
      GITHUB_IDENTITY_CLIENT_ID: "",
      GITHUB_IDENTITY_CLIENT_SECRET: "",
      DELIVERY_KEYRING_PROVIDER: "disabled",
      EMAIL_DELIVERY_PROVIDER: "disabled",
    },
  },
});
