/**
 * T10 S1 BLIND acceptance — the strategy definition layer (`strategy list`,
 * `strategy describe`, and the parameter/sizing contract `backtest run` honours).
 *
 * Written WITHOUT reading any of src/modules/paper-trading/backtest/**,
 * src/operations/**, src/mcp/**, src/cli/** or tests/t10-*.test.ts. Every
 * expectation below was derived from (a) SKILL.md, (b) the shipped fixture
 * tests/fixtures/t8/synthetic-series.json, and (c) running the CLI as a black
 * box and recording what came back. Nothing here imports production code — the
 * only seam used is the process boundary a real caller uses.
 *
 * The point of the seal is decorrelation: the implementer's own unit tests were
 * green while the CLI produced `fills: 0` twice on this exact path.
 */
import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

const ROOT = resolve(import.meta.dirname, "..");
const FIXTURE = join(ROOT, "tests/fixtures/t8/synthetic-series.json");
/** Every bar of the shipped fixture closes here; the sizing cases below key off it. */
const FIXTURE_CLOSE = 10_000;

type Envelope = { ok: boolean; command: string; result?: any; error?: { code: string; message: string } };

function cli(...args: string[]): { status: number; envelope: Envelope; raw: string } {
  const run = spawnSync("node", ["--import", "tsx", "src/cli/main.ts", ...args], {
    cwd: ROOT,
    encoding: "utf8",
    // A backtest of a few hundred bars is in-memory and fast; this only guards a hang.
    timeout: 60_000,
  });
  const raw = run.stdout ?? "";
  let envelope: Envelope;
  try {
    envelope = JSON.parse(raw);
  } catch {
    throw new Error(`CLI did not emit a JSON envelope for [${args.join(" ")}]\nstdout: ${raw}\nstderr: ${run.stderr}`);
  }
  return { status: run.status ?? -1, envelope, raw };
}

function backtest(series: string, strategy: string, cash: number, params?: unknown, extra: string[] = []) {
  const args = ["backtest", "run", "--series", series, "--strategy", strategy, "--cash", String(cash)];
  if (params !== undefined) args.push("--params", JSON.stringify(params));
  return cli(...args, ...extra, "--json");
}

// --- series construction (temp files; nothing lands in tests/fixtures) --------

let dir: string;
function series(name: string, closes: readonly number[], volume: number | readonly number[] = 1_000_000): string {
  const path = join(dir, `${name}.json`);
  writeFileSync(
    path,
    JSON.stringify({
      note: "SYNTHETIC — generated by tests/t10-blind-strategy.test.ts",
      instrument: "instr:BT",
      venue: "KRX",
      currency: "KRW",
      bars: closes.map((close, index) => ({
        periodStart: new Date(Date.UTC(2026, 0, 5 + index, 6, 30)).toISOString(),
        close,
        volume: typeof volume === "number" ? volume : volume[index],
        complete: true,
      })),
    }),
  );
  return path;
}

const ramp = (from: number, step: number, count: number): number[] =>
  Array.from({ length: count }, (_, i) => from + i * step);

let ONE_BAR: string;
let GAP_UP: string;
let THIN: string;
let DOWN_UP: string;
let DOWN_UP_DOWN: string;
let UP_DOWN: string;

beforeAll(() => {
  dir = mkdtempSync(join(tmpdir(), "t10-blind-"));
  ONE_BAR = series("one-bar", [FIXTURE_CLOSE]);
  // Bar 0 closes at 10 000, bar 1 gaps 5x. A market order placed on bar 0 reserves
  // against bar 0's price and cannot pay bar 1's — SKILL.md golden rule 3's case.
  GAP_UP = series("gap-up", [10_000, 50_000, 50_000]);
  THIN = series("thin", Array(10).fill(FIXTURE_CLOSE), 10);
  DOWN_UP = series("down-up", [...ramp(10_000, -100, 20), ...ramp(8_100, 200, 20)]);
  DOWN_UP_DOWN = series("down-up-down", [
    ...ramp(10_000, -100, 25),
    ...ramp(7_600, 300, 30),
    ...ramp(16_300, -300, 30),
  ]);
  UP_DOWN = series("up-down", [...ramp(8_000, 200, 20), ...ramp(11_800, -200, 25)]);
});

afterAll(() => {
  rmSync(dir, { recursive: true, force: true });
});

// ---------------------------------------------------------------------------
// A. the published surface
// ---------------------------------------------------------------------------

describe("S1 published strategy surface", () => {
  it("`strategy list` returns the documented envelope with exactly the two built-ins", () => {
    const { status, envelope } = cli("strategy", "list", "--json");
    expect(status).toBe(0);
    expect(envelope.ok).toBe(true);
    expect(envelope.command).toBe("strategy list");
    const names = envelope.result.strategies.map((s: any) => s.name);
    // SKILL.md 패턴 0: "내장 전략은 현재 buy_and_hold(기준선)와 sma_cross 둘뿐이다."
    expect(names).toEqual(["buy_and_hold", "sma_cross"]);
    for (const entry of envelope.result.strategies) {
      expect(typeof entry.summary).toBe("string");
      expect(entry.summary.length).toBeGreaterThan(0);
    }
  });

  it("every listed strategy is describable and describe agrees with list", () => {
    const listed = cli("strategy", "list", "--json").envelope.result.strategies;
    for (const entry of listed) {
      const { status, envelope } = cli("strategy", "describe", entry.name, "--json");
      expect(status).toBe(0);
      expect(envelope.ok).toBe(true);
      expect(envelope.result.name).toBe(entry.name);
      expect(envelope.result.summary).toBe(entry.summary);
      expect(envelope.result.params.type).toBe("object");
      expect(envelope.result.params.$schema).toContain("json-schema.org");
    }
  });

  it("sma_cross publishes fast/slow as required positive integers and a defaulted cashFraction", () => {
    const schema = cli("strategy", "describe", "sma_cross", "--json").envelope.result.params;
    expect(schema.required).toEqual(["fast", "slow"]);
    expect(schema.additionalProperties).toBe(false);
    expect(schema.properties.fast).toMatchObject({ type: "integer", exclusiveMinimum: 0 });
    expect(schema.properties.slow).toMatchObject({ type: "integer", exclusiveMinimum: 0 });
    expect(schema.properties.cashFraction).toMatchObject({ default: 0.95, exclusiveMinimum: 0, maximum: 1 });
  });

  it("buy_and_hold publishes only cashFraction and requires nothing", () => {
    const schema = cli("strategy", "describe", "buy_and_hold", "--json").envelope.result.params;
    expect(Object.keys(schema.properties)).toEqual(["cashFraction"]);
    expect(schema.required ?? []).toEqual([]);
    expect(schema.additionalProperties).toBe(false);
  });

  it("the generic `call` surface serves the identical definition (one definition, two surfaces)", () => {
    for (const name of ["buy_and_hold", "sma_cross"]) {
      const direct = cli("strategy", "describe", name, "--json").envelope.result;
      const generic = cli("call", "strategy.describe", "--input", JSON.stringify({ name }), "--json").envelope.result;
      expect(generic).toEqual(direct);
    }
    expect(cli("call", "strategy.list", "--input", "{}", "--json").envelope.result).toEqual(
      cli("strategy", "list", "--json").envelope.result,
    );
  });

  it("an unknown strategy name is a stable `usage` rejection that names the alternatives", () => {
    for (const probe of [
      ["strategy", "describe", "nope"],
      ["backtest", "run", "--series", FIXTURE, "--strategy", "nope", "--cash", "1000000"],
      // Casing and padding are not normalised — the caller must send the exact name.
      ["strategy", "describe", "BUY_AND_HOLD"],
      ["strategy", "describe", " buy_and_hold"],
    ]) {
      const { status, envelope } = cli(...probe, "--json");
      expect(status).toBe(1);
      expect(envelope.ok).toBe(false);
      expect(envelope.error?.code).toBe("usage");
      expect(envelope.error?.message).toContain("known: buy_and_hold, sma_cross");
    }
  });
});

// ---------------------------------------------------------------------------
// B. does the published schema describe what the engine actually accepts?
// ---------------------------------------------------------------------------

describe("S1 published schema vs. what the engine accepts", () => {
  it("rejects every single-field violation the schema forbids, with code `usage`", () => {
    const violations: Array<[string, unknown]> = [
      ["buy_and_hold", { nope: 1 }], // additionalProperties: false
      ["buy_and_hold", { cashFraction: "0.5" }], // type: number
      ["buy_and_hold", { cashFraction: null }],
      ["buy_and_hold", { cashFraction: 0 }], // exclusiveMinimum: 0
      ["buy_and_hold", { cashFraction: 1.5 }], // maximum: 1
      ["sma_cross", {}], // required: fast, slow
      ["sma_cross", { fast: 0, slow: 5 }],
      ["sma_cross", { fast: -1, slow: 5 }],
      ["sma_cross", { fast: 1.5, slow: 5 }], // type: integer
    ];
    for (const [strategy, params] of violations) {
      const { status, envelope } = backtest(FIXTURE, strategy, 10_000_000, params);
      expect(status, `${strategy} ${JSON.stringify(params)} should be rejected`).toBe(1);
      expect(envelope.error?.code).toBe("usage");
    }
    // 위반 9건 × CLI 자식 프로세스 1개. 호스트에선 여유롭지만 compose 레인에서는
    // 기본 5s 를 넘겼다. 느린 것이지 매달린 것이 아니다.
    // 실측: 이 파일 전체가 로컬 컨테이너 12.6s, GitHub 러너 47.4s. 러너가 3.8배 느리므로
    // 로컬 여유를 그대로 믿지 않고 러너 실측의 2.5배로 잡는다.
  }, 120_000);

  it("accepts the extremes the schema advertises as legal, and does not hang on them", () => {
    // cashFraction === 1 is the published maximum.
    const full = backtest(FIXTURE, "buy_and_hold", 10_000_000, { cashFraction: 1 });
    expect(full.status).toBe(0);
    expect(full.envelope.result.outcome.status).toBe("complete");
    // slow === the published maximum (2^53-1). A naive window allocation would die here.
    const huge = backtest(DOWN_UP, "sma_cross", 10_000_000, { fast: 1, slow: Number.MAX_SAFE_INTEGER });
    expect(huge.status).toBe(0);
    expect(huge.envelope.result.outcome.status).toBe("complete");
    expect(huge.envelope.result.outcome.fillCount).toBe(0);
  });

  it("enforces `fast < slow` at runtime even though JSON Schema cannot publish it (golden rule 5)", () => {
    const schema = cli("strategy", "describe", "sma_cross", "--json").envelope.result.params;
    expect(JSON.stringify(schema)).not.toContain("allOf");
    expect(JSON.stringify(schema)).not.toContain("dependent");
    for (const params of [{ fast: 5, slow: 2 }, { fast: 5, slow: 5 }]) {
      const { status, envelope } = backtest(FIXTURE, "sma_cross", 10_000_000, params);
      expect(status).toBe(1);
      expect(envelope.error?.code).toBe("usage");
      expect(envelope.error?.message).toContain("fast must be strictly less than slow");
    }
  });

  it("echoes the effective params (defaults applied), not the caller's input", () => {
    const dry = backtest(FIXTURE, "sma_cross", 100_000, { fast: 2, slow: 3 }, ["--dry-run"]);
    expect(dry.status).toBe(0);
    expect(dry.envelope.result.dryRun).toBe(true);
    expect(dry.envelope.result.strategy.params).toEqual({ fast: 2, slow: 3, cashFraction: 0.95 });
    expect(dry.envelope.result.series).toMatchObject({ barCount: 3, currency: "KRW", priceBasis: "raw" });

    const run = backtest(FIXTURE, "buy_and_hold", 10_000_000);
    expect(run.envelope.result.strategy.params).toEqual({ cashFraction: 0.95 });
  });
});

// ---------------------------------------------------------------------------
// C. sizing — the area that shipped broken twice
// ---------------------------------------------------------------------------

describe("S1 sizing", () => {
  it("buy_and_hold actually buys on the shipped fixture (the regression that shipped twice)", () => {
    const { status, envelope } = backtest(FIXTURE, "buy_and_hold", 10_000_000);
    expect(status).toBe(0);
    const outcome = envelope.result.outcome;
    expect(outcome.status).toBe("complete");
    expect(outcome.fillCount).toBeGreaterThan(0);
    expect(outcome.positions).toHaveLength(1);
    expect(outcome.positions[0].quantity).toBeGreaterThan(0);
    expect(outcome.refusals).toEqual([]);
    // The accuracy disclosure SKILL.md requires every caller to relay.
    expect(outcome).toMatchObject({ mode: "approximate", costModel: "none", priceBasis: "raw" });
  });

  it("fills are monotonic in seed cash — more money never buys strictly less", () => {
    const quantities = [10_000, 100_000, 1_000_000, 10_000_000].map((cash) => {
      const { envelope } = backtest(FIXTURE, "buy_and_hold", cash);
      const positions = envelope.result.outcome.positions;
      return positions.length === 0 ? 0 : positions[0].quantity;
    });
    for (let i = 1; i < quantities.length; i += 1) {
      expect(quantities[i], `quantities: ${quantities.join(",")}`).toBeGreaterThanOrEqual(quantities[i - 1]);
    }
    expect(quantities.at(-1)).toBeGreaterThan(0);
  });

  it("floor(cash*fraction/close) is an UPPER BOUND on the shares bought, as the schema says", () => {
    // Original blind assertion (2026-07-27) was that the engine BUYS whenever this
    // figure reaches 1. It does not, and the divergence is by design: sizing divides
    // by the reservation price (close lifted by the slippage ceiling, rounded up to
    // the tick), not by the close. Measured disagreement band on this fixture:
    // cash 10 527..10 554 at the default fraction, 10 001..10 024 at fraction 1.
    //
    // What was actually broken was the CONTRACT, not the engine: the cashFraction
    // description said "share of available cash to commit" and never mentioned the
    // padded price, so the naive figure read as exact. The description now publishes
    // the bound, and this test holds the engine to it.
    //
    // NOT covered here, and deliberately: inside the band the run is SILENT —
    // fillCount 0, orders 0, refusals 0, nothing says "sized to zero". Making that
    // visible needs a new StrategyAction kind and a report field, i.e. a guarded
    // public-contract change. Filed: .scratch/honesty-and-gates/open-findings.md.
    for (const cash of [10_000, 10_540, 10_600, 12_000, 100_000]) {
      const bound = Math.floor((cash * 0.95) / FIXTURE_CLOSE);
      const { status, envelope } = backtest(FIXTURE, "buy_and_hold", cash);
      expect(status).toBe(0);
      const positions = envelope.result.outcome.positions;
      const bought = positions.length === 0 ? 0 : positions[0].quantity;
      expect(bought, `cash=${cash} bound=${bound} bought=${bought}`).toBeLessThanOrEqual(bound);
    }
    // The bound is not vacuous — with real headroom the engine does buy.
    const ample = backtest(FIXTURE, "buy_and_hold", 100_000);
    expect(ample.envelope.result.outcome.positions[0].quantity).toBeGreaterThan(0);
  });

  it("an unfillable order is visible as an open order with reserved cash (golden rule 3)", () => {
    for (const [label, path, cash] of [
      ["gap up", GAP_UP, 11_000],
      ["no next bar to fill against", ONE_BAR, 10_000_000],
    ] as const) {
      const { status, envelope } = backtest(path, "buy_and_hold", cash);
      expect(status, label).toBe(0);
      const outcome = envelope.result.outcome;
      expect(outcome.status, label).toBe("complete");
      expect(outcome.fillCount, label).toBe(0);
      expect(outcome.orders, label).toHaveLength(1);
      expect(outcome.orders[0].execution, label).toBe("open");
      expect(outcome.cash[0].reserved, label).toBeGreaterThan(0);
      // "fillCount: 0 은 수익률 0% 가 아니다" — nothing was bought, so nothing moved.
      expect(outcome.positions, label).toEqual([]);
    }
  });

  it("thin volume throttles the fill and says so instead of pretending it filled", () => {
    const { status, envelope } = backtest(THIN, "buy_and_hold", 1_000_000_000);
    expect(status).toBe(0);
    const outcome = envelope.result.outcome;
    const order = outcome.orders[0];
    expect(order.execution).toBe("partially_filled");
    expect(order.filledQuantity).toBeLessThan(order.payload.quantity);
    expect(outcome.cash[0].reserved).toBeGreaterThan(0);
    // Participation is capped, so fillConfidence.maxParticipation has a ceiling —
    // a caller cannot ever see it exceed the cap, however unrealistic the order was.
    expect(outcome.performance.fillConfidence.maxParticipation).toBeLessThanOrEqual(0.1);
    expect(outcome.performance.fillConfidence.fills).toBe(outcome.fillCount);
  });
});

// ---------------------------------------------------------------------------
// D. sma_cross behaviour a caller depends on
// ---------------------------------------------------------------------------

describe("S1 sma_cross", () => {
  it("buys the golden cross and sells the death cross, which is what makes winRate computable", () => {
    const { status, envelope } = backtest(DOWN_UP_DOWN, "sma_cross", 10_000_000, { fast: 5, slow: 20 });
    expect(status).toBe(0);
    const outcome = envelope.result.outcome;
    const sides = outcome.orders.map((o: any) => o.payload.side);
    expect(sides).toEqual(["buy", "sell"]);
    expect(outcome.orders.every((o: any) => o.execution === "filled")).toBe(true);
    expect(new Date(outcome.orders[1].acceptedAt).getTime()).toBeGreaterThan(
      new Date(outcome.orders[0].acceptedAt).getTime(),
    );
    expect(outcome.positions).toEqual([]); // flat again after the death cross
    // Before a sell exists SKILL.md requires `no_sells`, not "0% win rate".
    expect(outcome.performance.winRate.status).toBe("covered");

    const heldToEnd = backtest(DOWN_UP, "sma_cross", 10_000_000, { fast: 5, slow: 20 });
    expect(heldToEnd.envelope.result.outcome.fillCount).toBe(1);
    expect(heldToEnd.envelope.result.outcome.performance.winRate).toEqual({
      status: "unavailable",
      reason: "no_sells",
    });
  });

  it("does nothing — without refusing — when no crossing is observable in the series", () => {
    // Windows longer than the series, and a series that is already above its slow
    // SMA at the first computable bar (monotone rise, then fall). Both are legal
    // input the engine completes silently: no refusal, no order, no fill.
    for (const [label, path, params] of [
      ["windows longer than 3-bar fixture", FIXTURE, { fast: 5, slow: 20 }],
      ["windows longer than a 40-bar series", DOWN_UP, { fast: 100, slow: 200 }],
      ["already above slow SMA at first computable bar", UP_DOWN, { fast: 5, slow: 20 }],
    ] as const) {
      const { status, envelope } = backtest(path, "sma_cross", 10_000_000, params);
      expect(status, label).toBe(0);
      const outcome = envelope.result.outcome;
      expect(outcome.status, label).toBe("complete");
      expect(outcome.fillCount, label).toBe(0);
      expect(outcome.orders, label).toEqual([]);
      expect(outcome.refusals, label).toEqual([]);
    }
  });
});

// ---------------------------------------------------------------------------
// E. the failure envelope a caller branches on
// ---------------------------------------------------------------------------

describe("S1 failure envelope", () => {
  it("separates a domain refusal (`refused`) from a bad call (`usage`)", () => {
    const empty = join(dir, "empty.json");
    writeFileSync(empty, JSON.stringify({ instrument: "instr:BT", venue: "KRX", currency: "KRW", bars: [] }));
    const refused = backtest(empty, "buy_and_hold", 10_000_000);
    expect(refused.status).toBe(1);
    expect(refused.envelope.error?.code).toBe("refused");
    expect(refused.envelope.error?.message).toContain("empty_series");

    const bad = backtest(FIXTURE, "buy_and_hold", 0);
    expect(bad.status).toBe(1);
    expect(bad.envelope.error?.code).toBe("usage");
  });

  it("echoes the command that was invoked in every envelope, success or failure", () => {
    // SKILL.md: "성공과 실패가 같은 envelope 을 쓴다" and its example failure envelope
    // carries `"command":"backtest run"`. Argument-shape failures instead return the
    // literal `"command":"usage"` — even though their own message names the command
    // ("strategy describe requires a strategy name"), so the command *was* resolved.
    // A caller correlating a batch of --json calls by `command` cannot place them.
    const cases: Array<[string[], string]> = [
      [["strategy", "list"], "strategy list"],
      [["strategy", "describe", "sma_cross"], "strategy describe"],
      [["strategy", "describe", "nope"], "strategy describe"],
      [["strategy", "describe"], "strategy describe"],
      [["backtest", "run", "--series", FIXTURE, "--strategy", "buy_and_hold", "--cash", "10000000"], "backtest run"],
      [["backtest", "run", "--series", FIXTURE, "--strategy", "buy_and_hold"], "backtest run"],
    ];
    for (const [args, expected] of cases) {
      const { envelope } = cli(...args, "--json");
      expect(envelope.command, `[${args.join(" ")}] -> ${JSON.stringify(envelope.error ?? {})}`).toBe(expected);
    }
  });

  it("never leaks series file contents into a failure message", () => {
    const secret = join(dir, "not-a-series.txt");
    writeFileSync(secret, "SUPER_SECRET_TOKEN=abc123\n");
    const { status, envelope, raw } = backtest(secret, "buy_and_hold", 10_000_000);
    expect(status).toBeGreaterThan(0);
    expect(raw).not.toContain("SUPER_SECRET_TOKEN");
    expect(envelope.ok).toBe(false);
  });
});
